package fd

import kore.fd.FList
import kore.wrap.*
import org.junit.Test
import kotlin.test.assertEquals
inline fun <ITEM:Any, OTHER:Any> List<ITEM>.transformOrDefault(
    default:()->OTHER,
    block:(List<ITEM>)->OTHER
):OTHER
= if(isNotEmpty()) block(this) else default()
class WListTest{
    @Test
    fun test1(){
        listOf(1, 2, 3, 4).transformOrDefault({0}){ it.sum() / it.size }
        val list = WList(1, 2, 3)
        val nil = WList<Int>()
        assertEquals(list.size, 3)
        assertEquals(nil.size, 0)
        assertEquals(list.toList(), listOf(1, 2, 3))
        assertEquals(list.setHead(5).toList(), listOf(5, 2, 3))
        assertEquals(nil.setHead(5).toString(), "Nil")
        assertEquals(list.setHeadW(W(5)).toList(), listOf(5, 2, 3))
        assertEquals(nil.setHeadW(W(5)).toString(), "Nil")
        assertEquals(list.setHeadW(W(Throwable(""))).toList(), listOf())
        assertEquals(nil.setHeadW(W(Throwable(""))).toString(), "Nil")
        assertEquals(list.fold(""){acc,it->acc + it}, "123")
        assertEquals(list.foldW(W("")){ acc, item->acc.map{"$it$item"} }(), "123")
        assertEquals(list.foldW(W("")){ acc, it->W.end() }.ok, null)
//        assertEquals(list.addFirst(4).toList(), listOf(4,1,2,3))
//        assertEquals(nil.addFirst(4).toString(), "Nil")
        assertEquals(list.foldIndexed(""){index, acc,it->"$acc$index$it"}, "011223")
        assertEquals(list.reverse().toList(), listOf(3,2,1))
        assertEquals(list.reverseW()()?.toList(), listOf(3,2,1))
        assertEquals(list.foldRight(""){it, acc->acc + it}, "321")
        assertEquals(list.foldRightW(W("")){item, acc->acc.map{"$it$item"}}(), "321")
        assertEquals(list.foldRightIndexed(""){index, it, acc->"$acc$index$it"}, "031221")
        assertEquals(list.map{"${it*2}"}.toList(), listOf("2","4","6"))
        assertEquals(list.flatMap{ if(it != 2) WList(it) else WList() }.toList(), listOf(1,3))
        assertEquals(WList(WList(1,2), WList(3,4)).flatten().toList(), listOf(1,2,3,4))
        assertEquals(list.appendW()()?.toList(), listOf(1,2,3))
        assertEquals(list.append().toList(), listOf(1,2,3))
        assertEquals(list.append(WList(4, 5)).toList(), listOf(1,2,3,4,5))
        assertEquals((list + WList.Nil).toList(), listOf(1,2,3))
        assertEquals((list + WList(4,5)).toList(), listOf(1,2,3,4,5))
        assertEquals(list.copy().toList(), listOf(1,2,3))
        assertEquals(list.appendW(W(WList(4, 5)))()?.toList(), listOf(1,2,3,4,5))
        assertEquals((list + W(WList.Nil))()?.toList(), listOf(1,2,3))
        assertEquals((list + W(WList(4,5)))()?.toList(), listOf(1,2,3,4,5))
        assertEquals(list.copyW()()?.toList(), listOf(1,2,3))
        assertEquals(list.drop(2).toList(), listOf(3))
        assertEquals(list.dropWhile { it < 2 }.toList(), listOf(2, 3))
        assertEquals(list.dropWhileIndexed { index, it -> index < 1 }.toList(), listOf(2, 3))
        assertEquals(list.dropLast().toList(), listOf(1,2))
        assertEquals(list.dropLast(2).toList(), listOf(1))
        assertEquals(list.dropLastWhile { it > 2 }.toList(), listOf(1,2))
        assertEquals(nil.dropLast().toList(), listOf())
        assertEquals(nil.dropLast(2).toList(), listOf())
        assertEquals(nil.dropLastWhile { it > 2 }.toList(), listOf())
        assertEquals(list.dropLastWhileIndexed { index, it ->index < 1}.toList(), listOf(1, 2))
        assertEquals(list.filter{it != 2}.toList(), listOf(1,3))
        assertEquals(WList(1, 2, 3, 4).filter{it % 2 == 0}.toList(), listOf(2,4))
        assertEquals(WList(1, 2, 3, 4).sliceFrom(3).toList(), listOf(3,4))
        assertEquals(WList(1, 2, 3, 4).slice(1).toList(), listOf(2,3,4))
        assertEquals(WList(1, 2, 3, 4).slice(1,2).toList(), listOf(2,3))
        assertEquals(nil.sliceFrom(3).toList(), listOf())
        assertEquals(nil.slice(1).toList(), listOf())
        assertEquals(nil.slice(1,2).toList(), listOf())
        assertEquals(list.startsWith(WList(2,3)), false)
        assertEquals(list.startsWith(WList(1,2,3)), true)
        assertEquals(list.startsWith(WList(1,3)), false)
        assertEquals(WList(1,2,3).startsWith(WList(1,2)), true)
        assertEquals(list.startsWith(WList()), true)
        assertEquals(nil.startsWith(WList()), true)
        assertEquals(nil.startsWith(WList(1,2)), false)
        assertEquals(WList(1,2) in list, true)
        assertEquals(WList(2,3) in list, true)
        assertEquals(WList(1,2,3) in list, true)
        assertEquals(WList(1,3) in list, false)
        assertEquals(WList() in list, false)
        assertEquals(WList(1,3) in nil, false)
        assertEquals(WList() in nil, true)
        assertEquals(1 in list, true)
        assertEquals(2 in list, true)
        assertEquals(3 in list, true)
        assertEquals(4 in list, false)
        assertEquals(1 in nil, false)
        assertEquals(WList.invoke(1, 2, 3).zipWith(WList.invoke(1,1,1)){ a, b->a + b}.toList(), listOf(2,3,4))
        assertEquals(WList.invoke(1, 2).zipWith(WList.invoke(1,1,1)){ a, b->a + b}.toList(), listOf(2,3))
        assertEquals(WList.invoke(1, 2, 3).zipWith(WList.invoke(1,1)){ a, b->a + b}.toList(), listOf(2,3))
    }

}